public enum SFXType
{
    largeExplosion,
    smallExplosion,
    bossAppears,
    bossStomps,
    buttonClick,
    letterSelect,
    letterDeselect,
    levelComplete,
    levelFailed,
    incorrectSubmission,
    correctSubmission,
    electricExplosion,
    bossPicksUpFoot,
    selectSound1,
    selectSound2,
    selectSound3,
    selectSound4,
    selectSound5,
    selectSound6,
    selectSound7,
    selectSound8,
    fallingBossSound,
    letterSpawn,
}

